Pave the way for Lucene 6.2.1 : SolrClient.shutdown() is removed in 6.2.1
1 failure with Lucene 6.2.1 :
java.lang.AssertionError: expected:<true> but was:<false>
	at org.apache.jena.query.text.TestDatasetWithAnalyzingQueryParser.testAnalyzingQueryParserAnalyzesWildcards(TestDatasetWithAnalyzingQueryParser.java:62)