Upgrade of Lucene to 5.5.3 : WIP
cf https://issues.apache.org/jira/browse/JENA-1250

Failed tests:
  TestDatasetWithLuceneMultilingualTextIndex.testEnglishStemming:189->AbstractTestDatasetWithTextIndexBase.doTestSearch:62->AbstractTestDatasetWithTextIndexBase.doTestSearch:66->AbstractTestDatasetWithTextIndexBase.doTestSearch:71->AbstractTestDatasetWithTextIndexBase.doTestQuery:104 expected:<true> but was:<false>
  TestDatasetWithLuceneMultilingualTextIndex.testRetrievingSKOSConcepts:236->AbstractTestDatasetWithTextIndexBase.doTestQuery:104 expected:<true> but was:<false>

Tests run: 170, Failures: 2, Errors: 0, Skipped: 0